services:
  - type: static
    name: lovelettertest
    runtime: static
    repo: https://github.com/tramnukyoyo/Lovelettertest
    branch: main
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
